import type { Metadata } from "next";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "USPG A_V",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body>
        {children}
      </body>
    </html>
  );
}
